#!/bin/sh

echo
echo "Checking commit message format..."
echo
if ! make lint-commit; then
    echo "See: https://www.conventionalcommits.org"
    echo "\033[31m============================================================================="
    exit 1
fi