// Code generated by tutone: DO NOT EDIT
package newrelic

import (
	"context"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/newrelic/newrelic-client-go/v2/pkg/errors"
	nrErrors "github.com/newrelic/newrelic-client-go/v2/pkg/errors"
)

func resourceNewRelicNotificationDestination() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceNewRelicNotificationDestinationCreate,
		ReadContext:   resourceNewRelicNotificationDestinationRead,
		UpdateContext: resourceNewRelicNotificationDestinationUpdate,
		DeleteContext: resourceNewRelicNotificationDestinationDelete,
		Schema: map[string]*schema.Schema{
			"auth": {
				Type:     schema.TypeList,
				
				Optional: true,
				
				
				
				Description: "auth\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
				
				
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"basic": {
							Type:     schema.TypeList,
							
							Optional: true,
							
							Description: "basic\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"custom_headers": {
							Type:     schema.TypeList,
							
							Optional: true,
							
							Description: "customHeaders\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"oauth2": {
							Type:     schema.TypeList,
							
							Optional: true,
							
							Description: "oauth2\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"token": {
							Type:     schema.TypeList,
							
							Optional: true,
							
							Description: "token\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"type": {
							Type:     schema.TypeString,
							Required: true,
							
							
							Description: "type\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						},
				},
				},
			"name": {
				Type:     schema.TypeString,
				Required: true,
				
				
				
				
				Description: "name\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
				
				
				},
			"properties": {
				Type:     schema.TypeList,
				Required: true,
				
				
				
				
				Description: "properties\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
				
				
				MaxItems: 0,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"display_value": {
							Type:     schema.TypeString,
							
							Optional: true,
							
							Description: "displayValue\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"key": {
							Type:     schema.TypeString,
							Required: true,
							
							
							Description: "key\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"label": {
							Type:     schema.TypeString,
							
							Optional: true,
							
							Description: "label\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"value": {
							Type:     schema.TypeString,
							Required: true,
							
							
							Description: "value\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						},
				},
				},
			"secure_url": {
				Type:     schema.TypeList,
				
				Optional: true,
				
				
				
				Description: "secureUrl\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
				
				
				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"prefix": {
							Type:     schema.TypeString,
							Required: true,
							
							
							Description: "prefix\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						"secure_suffix": {
							Type:     schema.TypeString,
							Required: true,
							
							
							Description: "secureSuffix\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
						},
						},
				},
				},
			"type": {
				Type:     schema.TypeString,
				Required: true,
				
				
				
				
				Description: "type\n\n---\n**NR Internal**\n\n * [#help-alerts](https://newrelic.slack.com/messages/C0DSAFF8Q)\n * Team ID: [439](https://team-store.datanerd.one/teams?teamId=439)\n\n* [bifrost repo](https://source.datanerd.us/newrelic-notifications/bifrost)\n\n* No additional info link provided\n\n * visibility(customer)\n\n",
				ValidateFunc: validation.StringInSlice([]string{
					"EMAIL","EVENT_BRIDGE","JIRA","MICROSOFT_TEAMS","MOBILE_PUSH","PAGERDUTY_ACCOUNT_INTEGRATION","PAGERDUTY_SERVICE_INTEGRATION","SERVICE_NOW","SERVICE_NOW_APP","SLACK","SLACK_COLLABORATION","SLACK_LEGACY","WEBHOOK","WORKFLOW_AUTOMATION",
				}, false),
				
				},
			},
	}
}

func resourceNewRelicNotificationDestinationCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	input := expandNewRelicNotificationDestinationCreateInput(d)
	result, err := client.Notifications.AiNotificationsCreateDestinationWithContext(ctx, accountID, input)
	if err != nil {
		return diag.FromErr(err)
	}
	if result == nil {
		return diag.Errorf("create returned nil result")
	}
	d.SetId(result.ID)
	return resourceNewRelicNotificationDestinationRead(ctx, d, meta)
}

func resourceNewRelicNotificationDestinationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	filter := AiNotificationsDestinationFilter{
		ID: d.Id(),
	}
	response, err := client.Notifications.GetDestinationsWithContextAccount(ctx, accountID, filter)
	if err != nil {
		return diag.FromErr(err)
	}
	if response == nil || len(response.Entities) == 0 {
		d.SetId("")
		return nil
	}
	return diag.FromErr(flattenNewRelicNotificationDestination(&response.Entities[0], d))
	}

func resourceNewRelicNotificationDestinationUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	input := expandNewRelicNotificationDestinationUpdateInput(d)
	_, err := = client.Notifications.AiNotificationsUpdateDestinationWithContext(ctx, accountID, d.Id(), input)
	if err != nil {
		return diag.FromErr(err)
	}

	return resourceNewRelicNotificationDestinationRead(ctx, d, meta)
}
func resourceNewRelicNotificationDestinationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	_, err := client.Notifications.AiNotificationsDeleteDestinationWithContext(ctx, accountID, d.Id())
	if err != nil {
		if _, ok := err.(*nrErrors.NotFound); ok {
			return nil
		}
		return diag.FromErr(err)
	}

	return nil
}
