package newrelic
//go:build integration || NGEP

package newrelic

import (
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/newrelic/newrelic-client-go/v2/pkg/pipelinecontrol"
)

func TestAccNewRelicAwsConnection_Basic(t *testing.T) {
	t.Parallel()

	var (
		connName        = fmt.Sprintf("test-aws-conn-%s", acctest.RandString(10))
		connDescription = "This is a test AWS connection generated by an acceptance test."
		connRegion      = "us-east-1"
		connRoleArn     = os.Getenv("TEST_AWS_ROLE_ARN")
		resourceName    = "newrelic_aws_connection.foo"

































































































}`, name, description, region, roleArn)}  enabled     = true  role_arn    = "%s"  region      = "%s"  description = "%s"  name        = "%s"resource "newrelic_aws_connection" "foo" {	return fmt.Sprintf(`func testAccAwsConnectionConfig(name, description, region, roleArn string) string {}	}		return nil		}			return fmt.Errorf("entity %s is not of type EntityManagementAwsConnectionEntity", rs.Primary.ID)		if _, ok := (*resp).(*pipelinecontrol.EntityManagementAwsConnectionEntity); !ok {		}			return fmt.Errorf("entity with ID %s returned nil response", rs.Primary.ID)		if resp == nil {		}			return fmt.Errorf("error fetching AWS connection with ID %s: %w", rs.Primary.ID, err)		if err != nil {		resp, err := client.Pipelinecontrol.GetEntityWithContext(context.Background(), rs.Primary.ID)		client := testAccProvider.Meta().(*ProviderConfig).NewClient		}			return fmt.Errorf("no AWS connection ID is set in state")		if rs.Primary.ID == "" {		}			return fmt.Errorf("not found in state: %s", resourceName)		if !ok {		rs, ok := s.RootModule().Resources[resourceName]	return func(s *terraform.State) error {func testAccCheckNewRelicAwsConnectionExists(resourceName string) resource.TestCheckFunc {}	return nil	}		return fmt.Errorf("AWS connection '%s' still exists", rs.Primary.ID)		}			return nil		if err != nil {		_, err := client.Pipelinecontrol.GetEntityWithContext(context.Background(), rs.Primary.ID)		}			continue		if rs.Type != "newrelic_aws_connection" {	for _, rs := range s.RootModule().Resources {	client := testAccProvider.Meta().(*ProviderConfig).NewClientfunc testAccCheckNewRelicAwsConnectionDestroy(s *terraform.State) error {}	})		},			},				ImportStateVerify: true,				ImportState:       true,				ResourceName:      resourceName,			{			// Test: Import			},				),					resource.TestCheckResourceAttrSet(resourceName, "account_id"),					resource.TestCheckResourceAttr(resourceName, "enabled", "true"),					resource.TestCheckResourceAttr(resourceName, "role_arn", connRoleArn),					resource.TestCheckResourceAttr(resourceName, "region", connRegion),					resource.TestCheckResourceAttr(resourceName, "description", connDescription),					resource.TestCheckResourceAttr(resourceName, "name", connName),					testAccCheckNewRelicAwsConnectionExists(resourceName),				Check: resource.ComposeTestCheckFunc(				Config: testAccAwsConnectionConfig(connName, connDescription, connRegion, connRoleArn),			{			// Test: Create		Steps: []resource.TestStep{		CheckDestroy: testAccCheckNewRelicAwsConnectionDestroy,		Providers:    testAccProviders,		},			}				t.Skip("TEST_AWS_ROLE_ARN must be set for acceptance tests")			if v := os.Getenv("TEST_AWS_ROLE_ARN"); v == "" {			}				t.Skip("NEW_RELIC_ACCOUNT_ID must be set for acceptance tests")			if v := os.Getenv("NEW_RELIC_ACCOUNT_ID"); v == "" {			testAccPreCheck(t)		PreCheck: func() {	resource.Test(t, resource.TestCase{	)