// Code generated by tutone — edit this file.
package newrelic

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
)

func TestAccNewRelicNotificationDestination_basic(t *testing.T) {
	// TUTONE:MANUAL — fill in test config and check functions
	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckNewRelicNotificationDestinationDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccNewRelicNotificationDestinationConfig(),
				Check:  resource.ComposeTestCheckFunc(),
			},
		},
	})
}

func testAccNewRelicNotificationDestinationConfig() string {
	// TUTONE:MANUAL
	return ""
}

func testAccCheckNewRelicNotificationDestinationDestroy(s interface{}) error {
	// TUTONE:MANUAL
	return nil
}
