package newrelic

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/newrelic/newrelic-client-go/v2/pkg/changetracking"
	"github.com/newrelic/newrelic-client-go/v2/pkg/common"
)

func resourceNewRelicChangeTrackingEvent() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceNewRelicChangeTrackingEventCreate,
		ReadContext:   schema.NoopContext,
		Delete:        schema.RemoveFromState,
		Schema: map[string]*schema.Schema{
			"version": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The version of the deployed software.",
			},
			"entity_guid": {
				Type:        schema.TypeString,
				Required:    true,
				ForceNew:    true,
				Description: "The GUID of the entity the change tracking event is associated with.",
			},
			"changelog": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "A URL to the changelog or, if not linkable, a list of changes.",
			},
			"commit": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The commit identifier, for example, a Git commit SHA.",
			},
			"deep_link": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "A URL to the system that generated the deployment.",
			},
			"deployment_type": {
				Type:         schema.TypeString,
				Optional:     true,
				ForceNew:     true,
				ValidateFunc: validation.StringInSlice(listValidChangeTrackingDeploymentTypes(), false),
				Description:  "The type of deployment.",
			},
			"description": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "A description of the deployment.",
			},
			"group_id": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "An identifier used to correlate account-wide changes across entities.",
			},
			"timestamp": {
				Type:        schema.TypeInt,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "The start time of the deployment as the number of milliseconds since the Unix epoch. Defaults to now.",
			},
			"user": {
				Type:        schema.TypeString,
				Optional:    true,
				ForceNew:    true,
				Description: "The username of the deployer or bot.",
			},
			"deployment_id": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "The unique deployment identifier generated by New Relic.",
			},
		},
	}
}

func listValidChangeTrackingDeploymentTypes() []string {
	return []string{
		string(changetracking.ChangeTrackingDeploymentTypeTypes.BASIC),
		string(changetracking.ChangeTrackingDeploymentTypeTypes.BLUE_GREEN),
		string(changetracking.ChangeTrackingDeploymentTypeTypes.CANARY),
		string(changetracking.ChangeTrackingDeploymentTypeTypes.OTHER),
		string(changetracking.ChangeTrackingDeploymentTypeTypes.ROLLING),
		string(changetracking.ChangeTrackingDeploymentTypeTypes.SHADOW),
	}
}

var _ = common.EntityGUID("")
var _ = log.Printf
var _ = diag.FromErr
var _ = context.Background

func resourceNewRelicChangeTrackingEventCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient

	changeTrackingEvent, dataHandlingRules, err := expandChangeTrackingEvent(d)
	if err != nil {
		return diag.FromErr(err)
	}

	log.Printf("[INFO] Creating New Relic change tracking event")

	result, err := client.ChangeTracking.ChangeTrackingCreateEventWithContext(ctx, changeTrackingEvent, dataHandlingRules)
	if err != nil {
		return diag.FromErr(err)
	}

	d.SetId(result.ChangeTrackingEvent.(interface{ GetChangeTrackingId() string }).GetChangeTrackingId())
	return nil
}
