// Code generated by tutone — DO NOT EDIT
// Resource: newrelic_pathpoint_flow
//
// TUTONE:STATUS ✅ FULLY AUTOMATED — no manual changes required; ready to merge
package newrelic

import (
	"context"
	"log"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	nrErrors "github.com/newrelic/newrelic-client-go/v2/pkg/errors"
)

func resourceNewRelicPathpointFlow() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceNewRelicPathpointFlowCreate,
		ReadContext:   resourceNewRelicPathpointFlowRead,
		UpdateContext: resourceNewRelicPathpointFlowUpdate,
		DeleteContext: resourceNewRelicPathpointFlowDelete,
		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
		Schema: map[string]*schema.Schema{

			"account_id": {
				Type:        schema.TypeInt,
				Optional:    true,
				Computed:    true,
				Description: "The New Relic account ID to operate on. Defaults to the account set in the provider.",
			},
		},
	}
}

func resourceNewRelicPathpointFlowCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*ProviderConfig).NewClient
	accountID := selectAccountID(meta.(*ProviderConfig), d)
	pathpointInput := expandNewRelicPathpointFlowCreateInput(d)
	scopeInput := expandNewRelicPathpointFlowScopeInput(d)
	result, err := client.PathPoint.PathPointCreate(pathpointInput, scopeInput)
	if err != nil {
		return diag.FromErr(err)
	}
	if result == nil {
		return diag.Errorf("create returned nil")
	}
	d.SetId(string(result.ID))

	return resourceNewRelicPathpointFlowRead(ctx, d, meta)
}

func resourceNewRelicPathpointFlowRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*ProviderConfig).NewClient
	accountID := selectAccountID(meta.(*ProviderConfig), d)
	id := d.Id()

	log.Printf("[INFO] Reading newrelic_pathpoint_flow %v", id)
	result, err := client.PathPoint.GetFlow(accountID, id)
	if err != nil {
		if _, ok := err.(*nrErrors.NotFound); ok {
			d.SetId("")
			return nil
		}
		return diag.FromErr(err)
	}
	if result == nil {
		d.SetId("")
		return nil
	}

	return diag.FromErr(flattenNewRelicPathpointFlow(result, d))
}
func resourceNewRelicPathpointFlowUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*ProviderConfig).NewClient
	id := d.Id()

	log.Printf("[INFO] Updating newrelic_pathpoint_flow %v", id)
	input := expandNewRelicPathpointFlowUpdateInput(d)

	_, updateErr := client.PathPoint.PathPointUpdate(id, input)
	if updateErr != nil {
		return diag.FromErr(updateErr)
	}

	return resourceNewRelicPathpointFlowRead(ctx, d, meta)
}

func resourceNewRelicPathpointFlowDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*ProviderConfig).NewClient
	id := d.Id()

	log.Printf("[INFO] Deleting newrelic_pathpoint_flow %v", id)
	deleteErr := client.PathPoint.PathPointDelete(id)
	if deleteErr != nil {
		if _, ok := deleteErr.(*nrErrors.NotFound); ok {
			return nil
		}
		return diag.FromErr(deleteErr)
	}

	return nil
}
