//go:build integration || NGEP

package newrelic

import (
	"context"
	"fmt"
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"

	"github.com/newrelic/newrelic-client-go/v2/pkg/pipelinecontrol"
)

func TestAccNewRelicAwsConnection_Basic(t *testing.T) {
	t.Parallel()

	if v := os.Getenv("TEST_AWS_ROLE_ARN"); v == "" {
		t.Skip("TEST_AWS_ROLE_ARN must be set for acceptance tests")
	}
	if v := os.Getenv("NEW_RELIC_ACCOUNT_ID"); v == "" {
		t.Skip("NEW_RELIC_ACCOUNT_ID must be set for acceptance tests")
	}

	connName := fmt.Sprintf("test-aws-conn-%s", acctest.RandString(10))
	connDescription := "This is a test AWS connection generated by an acceptance test."
	connRegion := "us-east-1"
	connRoleArn := os.Getenv("TEST_AWS_ROLE_ARN")
	resourceName := "newrelic_aws_connection.foo"

	resource.Test(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckNewRelicAwsConnectionDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAwsConnectionConfig(connName, connDescription, connRegion, connRoleArn),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet(resourceName, "account_id"),
					resource.TestCheckResourceAttr(resourceName, "enabled", "true"),
					resource.TestCheckResourceAttr(resourceName, "role_arn", connRoleArn),
					resource.TestCheckResourceAttr(resourceName, "region", connRegion),
					resource.TestCheckResourceAttr(resourceName, "description", connDescription),
					resource.TestCheckResourceAttr(resourceName, "name", connName),
					testAccCheckNewRelicAwsConnectionExists(resourceName),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccCheckNewRelicAwsConnectionExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("not found in state: %s", resourceName)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no AWS connection ID is set in state")
		}

		client := testAccProvider.Meta().(*ProviderConfig).NewClient
		resp, err := client.Pipelinecontrol.GetEntityWithContext(context.Background(), rs.Primary.ID)
		if err != nil {
			return fmt.Errorf("error fetching AWS connection with ID %s: %w", rs.Primary.ID, err)
		}
		if resp == nil {
			return fmt.Errorf("entity with ID %s returned nil response", rs.Primary.ID)
		}
		if _, ok := (*resp).(*pipelinecontrol.EntityManagementAwsConnectionEntity); !ok {
			return fmt.Errorf("entity %s is not of type EntityManagementAwsConnectionEntity", rs.Primary.ID)
		}
		return nil
	}
}

func testAccCheckNewRelicAwsConnectionDestroy(s *terraform.State) error {
	client := testAccProvider.Meta().(*ProviderConfig).NewClient
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "newrelic_aws_connection" {
			continue
		}
		_, err := client.Pipelinecontrol.GetEntityWithContext(context.Background(), rs.Primary.ID)
		if err == nil {
			return fmt.Errorf("AWS connection '%s' still exists", rs.Primary.ID)
		}
	}
	return nil
}

func testAccAwsConnectionConfig(name, description, region, roleArn string) string {
	return fmt.Sprintf(`
resource "newrelic_aws_connection" "foo" {
  enabled     = true
  role_arn    = "%s"
  region      = "%s"
  description = "%s"
  name        = "%s"
}
`, roleArn, region, description, name)
}
