//go:build integration || unit || PATHPOINT

// Test helpers for newrelic_pathpoint_flow
// Code generated by tutone — scaffold only, safe to edit
package newrelic

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/acctest"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	"github.com/hashicorp/terraform-plugin-sdk/v2/terraform"
)

func testAccCheckNewRelicPathpointFlowDestroy(s *terraform.State) error {
	client := testAccProvider.Meta().(*ProviderConfig).NewClient
	for _, r := range s.RootModule().Resources {
		if r.Type != "newrelic_pathpoint_flow" {
			continue
		}
		id := r.Primary.ID
		_ = client
		_ = id
		// TUTONE:MANUAL — add destroy verification using the Read API call
	}
	return nil
}

func testAccCheckNewRelicPathpointFlowExists(n string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[n]
		if !ok {
			return fmt.Errorf("not found: %s", n)
		}
		if rs.Primary.ID == "" {
			return fmt.Errorf("no ID set for newrelic_pathpoint_flow")
		}
		// TUTONE:MANUAL — add existence verification
		return nil
	}
}

func TestAccNewRelicPathpointFlow_Basic(t *testing.T) {
	resourceName := "newrelic_pathpoint_flow.test"
	rName := acctest.RandString(5)
	_ = rName

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckNewRelicPathpointFlowDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccNewRelicPathpointFlowConfig(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNewRelicPathpointFlowExists(resourceName),
				),
			},
			{
				Config: testAccNewRelicPathpointFlowConfigUpdated(rName),
				Check: resource.ComposeTestCheckFunc(
					testAccCheckNewRelicPathpointFlowExists(resourceName),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

// TUTONE:MANUAL — write HCL config helpers below

func testAccNewRelicPathpointFlowConfig(name string) string {
	return fmt.Sprintf(`
resource "newrelic_pathpoint_flow" "test" {
  # TUTONE:MANUAL — add required fields
}
`, name)
}
func testAccNewRelicPathpointFlowConfigUpdated(name string) string {
	return fmt.Sprintf(`
resource "newrelic_pathpoint_flow" "test" {
  # TUTONE:MANUAL — add updated fields
}
`, name)
}
