// Code generated by tutone: DO NOT EDIT
package newrelic

import (
	"context"
	"strconv"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	nrErrors "github.com/newrelic/newrelic-client-go/v2/pkg/errors"
)

func resourceNewRelicMaintenanceWindow() *schema.Resource {
	return &schema.Resource{
		CreateContext: resourceNewRelicMaintenanceWindowCreate,
		ReadContext:   resourceNewRelicMaintenanceWindowRead,
		UpdateContext: resourceNewRelicMaintenanceWindowUpdate,
		DeleteContext: resourceNewRelicMaintenanceWindowDelete,
		Schema: map[string]*schema.Schema{
			"affected_entities": {
				Type: schema.TypeList,

				Optional: true,

				Description: "The entities affected by the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",

				Elem: &schema.Schema{
					Type: schema.TypeString,
				},
			},
			"affected_entity_type": {
				Type:     schema.TypeString,
				Required: true,

				Description: "The type of the entities affected by maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
				ValidateFunc: validation.StringInSlice([]string{
					"SERVICE_LEVEL",
				}, false),
			},
			"description": {
				Type: schema.TypeString,

				Optional: true,

				Description: "The description of the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
			"duration": {
				Type:     schema.TypeString,
				Required: true,

				Description: "The duration of the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
			"name": {
				Type:     schema.TypeString,
				Required: true,

				Description: "The name of the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
			"rrule": {
				Type: schema.TypeString,

				Optional: true,

				Description: "The Recurrence Rule of the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
			"scope": {
				Type:     schema.TypeList,
				Required: true,

				Description: "The scope the maintenance window belongs to.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",

				MaxItems: 1,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:     schema.TypeString,
							Required: true,

							Description: "Scope id of the entity\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
						},
						"type": {
							Type:     schema.TypeString,
							Required: true,

							Description: "Scope type of the entity\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
						},
					},
				},
			},
			"start_time": {
				Type:     schema.TypeString,
				Required: true,

				Description: "The start time of the maintenance window in ISO 8601 format.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
			"timezone": {
				Type:     schema.TypeString,
				Required: true,

				Description: "The timezone of the maintenance window.\n\n---\n**NR Internal**\n\n * [#help-service-levels](https://newrelic.enterprise.slack.com/archives/C01NCTZ9M6U)\n * Team ID: [718](https://team-store.datanerd.one/teams?teamId=718)\n\n* [maintenance-window-service repo](https://source.datanerd.us/service-levels/maintenance-window-service)\n\n* No additional info link provided\n\n * visibility(flag:`NR1/service_levels_management__downtimes`)\n\n",
			},
		},
	}
}

func resourceNewRelicMaintenanceWindowCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	input := expandNewRelicMaintenanceWindowCreateInput(d)
	result, err := client.Maintenancewindow.MaintenanceWindowCreateWithContext(ctx, accountID, input)
	if err != nil {
		return diag.FromErr(err)
	}
	if result == nil {
		return diag.Errorf("create returned nil result")
	}
	d.SetId(strconv.Itoa(result.ID))
	return resourceNewRelicMaintenanceWindowRead(ctx, d, meta)
}

func resourceNewRelicMaintenanceWindowRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	id, err := strconv.Atoi(d.Id())
	if err != nil {
		return diag.FromErr(err)
	}
	result, err := client.Maintenancewindow.GetMaintenanceWindowWithContext(ctx, accountID, id)
	if err != nil {
		if _, ok := err.(*nrErrors.NotFound); ok {
			d.SetId("")
			return nil
		}
		return diag.FromErr(err)
	}
	if result == nil {
		d.SetId("")
		return nil
	}
	return diag.FromErr(flattenNewRelicMaintenanceWindow(result, d))
}

func resourceNewRelicMaintenanceWindowUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	id, err := strconv.Atoi(d.Id())
	if err != nil {
		return diag.FromErr(err)
	}
	input := expandNewRelicMaintenanceWindowUpdateInput(d)
	_, err = client.Maintenancewindow.MaintenanceWindowUpdateWithContext(ctx, accountID, id, input)
	if err != nil {
		return diag.FromErr(err)
	}

	return resourceNewRelicMaintenanceWindowRead(ctx, d, meta)
}
func resourceNewRelicMaintenanceWindowDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	providerConfig := meta.(*ProviderConfig)
	client := providerConfig.NewClient
	accountID := selectAccountID(providerConfig, d)
	id, err := strconv.Atoi(d.Id())
	if err != nil {
		return diag.FromErr(err)
	}
	_, err = client.Maintenancewindow.MaintenanceWindowDeleteWithContext(ctx, accountID, id)
	if err != nil {
		if _, ok := err.(*nrErrors.NotFound); ok {
			return nil
		}
		return diag.FromErr(err)
	}

	return nil
}
