// Code generated by tutone: DO NOT EDIT
package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func expandNewRelicNotificationDestinationCreateInput(d *schema.ResourceData) interface{} {
	// TUTONE:MANUAL — replace return type with AiNotificationsDestinationInput and implement expansion
	return nil
}

func expandNewRelicNotificationDestinationUpdateInput(d *schema.ResourceData) interface{} {
	// TUTONE:MANUAL — replace return type with AiNotificationsDestinationUpdate and implement expansion
	return nil
}
func flattenNewRelicNotificationDestination(obj interface{}, d *schema.ResourceData) error {
	if obj == nil {
		return nil
	}
	// d.Set("auth", obj.Auth)
	// d.Set("name", obj.Name)
	// d.Set("properties", obj.Properties)
	// d.Set("secure_url", obj.SecureURL)
	// d.Set("type", obj.Type)
	// TUTONE:MANUAL — implement flattenNewRelicNotificationDestination
	return nil
}

func expandNewRelicNotificationDestinationAuth(in []interface{}) interface{} {
	if len(in) == 0 || in[0] == nil {
		return nil
	}
	// TUTONE:MANUAL — expand auth
	return nil
}
func expandNewRelicNotificationDestinationProperties(in []interface{}) interface{} {
	if len(in) == 0 || in[0] == nil {
		return nil
	}
	// TUTONE:MANUAL — expand properties
	return nil
}
func expandNewRelicNotificationDestinationSecureURL(in []interface{}) interface{} {
	if len(in) == 0 || in[0] == nil {
		return nil
	}
	// TUTONE:MANUAL — expand secure_url
	return nil
}
