// Code generated by tutone — DO NOT EDIT
// Structures: newrelic_pathpoint_flow
//
// TUTONE:STATUS ✅ FULLY AUTOMATED — no manual changes required; ready to merge
package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/newrelic/newrelic-client-go/v2/pkg/pathpoint"
)

// expandNewRelicPathpointFlowCreateInput builds the create API input from Terraform state.
// TUTONE:AUTO — fully generated
func expandNewRelicPathpointFlowCreateInput(d *schema.ResourceData) pathpoint.PathPointFlowInput {
	input := pathpoint.PathPointFlowInput{}
	return input
}

// expandNewRelicPathpointFlowScopeInput builds the scope input from Terraform state.
// TUTONE:AUTO — fully generated
func expandNewRelicPathpointFlowScopeInput(d *schema.ResourceData) pathpoint.PathPointScopeInput {
	input := pathpoint.PathPointScopeInput{}
	if v, ok := d.GetOk("scope"); ok {
		list := v.([]interface{})
		if len(list) > 0 {
			cfg := list[0].(map[string]interface{})
			_ = cfg // populated by fields below; kept in case SchemaFields is empty at generation time
		}
	}
	return input
}

// expandNewRelicPathpointFlowUpdateInput builds the update API input from Terraform state.
// TUTONE:AUTO — fully generated
func expandNewRelicPathpointFlowUpdateInput(d *schema.ResourceData) pathpoint.PathPointFlowResult {
	input := pathpoint.PathPointFlowResult{}
	return input
}

// flattenNewRelicPathpointFlow writes the API response into Terraform state.
// TUTONE:AUTO — fully generated
func flattenNewRelicPathpointFlow(result *pathpoint.PathPointFlowResult, d *schema.ResourceData) error {
	if err := d.Set("account_id", result.AccountID); err != nil {
		return err
	}
	return nil
}
