package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/newrelic/newrelic-client-go/v2/pkg/workflows"
)

// STUB — generated by local NerdCompletionClientStub

func expandStub(d *schema.ResourceData) *workflows.AiWorkflowsCreateWorkflowInput {
	return &workflows.AiWorkflowsCreateWorkflowInput{
		Name: d.Get("name").(string),
	}
}

func flattenStub(result *workflows.AiWorkflowsWorkflow, d *schema.ResourceData) error {
	d.Set("name", result.Name)
	return nil
}

package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/newrelic/newrelic-client-go/v2/pkg/workflows"
)

// STUB — generated by local NerdCompletionClientStub

func expandStub(d *schema.ResourceData) *workflows.AiWorkflowsCreateWorkflowInput {
	return &workflows.AiWorkflowsCreateWorkflowInput{
		Name: d.Get("name").(string),
	}
}

func flattenStub(result *workflows.AiWorkflowsWorkflow, d *schema.ResourceData) error {
	d.Set("name", result.Name)
	return nil
}
