// Code generated by tutone: DO NOT EDIT
package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

func expandNewRelicMaintenanceWindowCreateInput(d *schema.ResourceData) interface{} {
	// TUTONE:MANUAL — replace return type with MaintenanceWindowConfigCreateInput and implement expansion
	return nil
}

func expandNewRelicMaintenanceWindowUpdateInput(d *schema.ResourceData) interface{} {
	// TUTONE:MANUAL — replace return type with MaintenanceWindowConfigUpdateInput and implement expansion
	return nil
}
func flattenNewRelicMaintenanceWindow(obj interface{}, d *schema.ResourceData) error {
	if obj == nil {
		return nil
	}
	// d.Set("affected_entities", obj.AffectedEntities)
	// d.Set("affected_entity_type", obj.AffectedEntityType)
	// d.Set("description", obj.Description)
	// d.Set("duration", obj.Duration)
	// d.Set("name", obj.Name)
	// d.Set("rrule", obj.Rrule)
	// d.Set("scope", obj.Scope)
	// d.Set("start_time", obj.StartTime)
	// d.Set("timezone", obj.Timezone)
	// TUTONE:MANUAL — implement flattenNewRelicMaintenanceWindow
	return nil
}

func expandNewRelicMaintenanceWindowScope(in []interface{}) interface{} {
	if len(in) == 0 || in[0] == nil {
		return nil
	}
	// TUTONE:MANUAL — expand scope
	return nil
}
