// Code generated by tutone: DO NOT EDIT
package newrelic

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/newrelic/newrelic-client-go/v2/pkg/maintenancewindow"
)

func expandNewRelicMaintenanceWindowCreateInput(d *schema.ResourceData) maintenancewindow.MaintenanceWindowConfigCreateInput {
	// TUTONE:MANUAL — implement expansion
	return maintenancewindow.MaintenanceWindowConfigCreateInput{}
}

func expandNewRelicMaintenanceWindowUpdateInput(d *schema.ResourceData) maintenancewindow.MaintenanceWindowConfigUpdateInput {
	// TUTONE:MANUAL — implement expansion
	return maintenancewindow.MaintenanceWindowConfigUpdateInput{}
}
func flattenNewRelicMaintenanceWindow(obj *maintenancewindow.MaintenanceWindowConfigDefinition, d *schema.ResourceData) error {
	if obj == nil {
		return nil
	}
	// d.Set("affected_entities", obj.AffectedEntities)
	// d.Set("affected_entity_type", obj.AffectedEntityType)
	// d.Set("description", obj.Description)
	// d.Set("duration", obj.Duration)
	// d.Set("name", obj.Name)
	// d.Set("rrule", obj.Rrule)
	// d.Set("scope", obj.Scope)
	// d.Set("start_time", obj.StartTime)
	// d.Set("timezone", obj.Timezone)
	// TUTONE:MANUAL — implement flattenNewRelicMaintenanceWindow
	return nil
}

func expandNewRelicMaintenanceWindowScope(in []interface{}) maintenancewindow.Scope {
	if len(in) == 0 || in[0] == nil {
		return maintenancewindow.Scope{}
	}
	// TUTONE:MANUAL — expand scope
	return maintenancewindow.Scope{}
}
