name: PR Title Conventional Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    name: PR Title Conventional Check
    runs-on: ubuntu-latest
    steps:
      - name: Conventional PR Title Check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: true