name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commits
        id: get-commits
        run: |
          # Get the base and head SHAs
          base_sha=$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          head_sha=${{ github.event.pull_request.head.sha }}
          
          # Store invalid commits in a variable
          invalid_commits=""
          
          # Check each commit
          while read -r commit; do
            commit_msg=$(git log -1 --format=%B "$commit")
            # Conventional commit regex pattern
            if ! echo "$commit_msg" | grep -qP '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9-]+\))?: .+$'; then
              commit_info="$(git log -1 --format='%H - %s' $commit)"
              invalid_commits="$invalid_commits\n$commit_info"
            fi
          done < <(git rev-list $base_sha..$head_sha)
          
          # Set output
          if [ ! -z "$invalid_commits" ]; then
            echo "invalid_commits<<EOF" >> $GITHUB_OUTPUT
            echo -e "$invalid_commits" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "has_invalid=true" >> $GITHUB_OUTPUT
          else
            echo "has_invalid=false" >> $GITHUB_OUTPUT
          fi
      - name: Comment PR
        if: steps.get-commits.outputs.has_invalid == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const invalidCommits = `${{ steps.get-commits.outputs.invalid_commits }}`;
            const message = `### ❌ Invalid Conventional Commits Detected
            
            The following commits do not follow the [Conventional Commits](https://www.conventionalcommits.org/) format:

            - ${invalidCommits}
            
            
            Please update these commit messages to follow the format:
            \`<type>[optional scope]: <description>\`
            
            Valid types: build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
            core.setFailed('Some commits do not follow conventional commit format');